"""Provisional subject-level train/val split (Role A).

**Provisional.** Role C owns the real split. This script exists so that
``scripts/crop_stats.py`` has a *training-only* subject list to derive
``configs/crop.yaml`` from, instead of quietly using all 200 subjects (which
would leak validation landmarks into a frozen preprocessing parameter).

It implements Role C's documented default: 160 train / 40 val, ``numpy``
``default_rng(42)``. IDs are sorted before shuffling, so the split is a pure
function of (the set of subject IDs, the seed) and is reproducible on any
machine. The split is **subject level**: a subject's left and right ear always
land in the same fold by construction, because the unit being split is the
subject ID and both ears are derived from it.

Writes ``splits/train_ids.txt`` and ``splits/val_ids.txt`` (one subject ID per
line, sorted) plus ``splits/README.md``. Those files contain IDs only — no
coordinates, no mesh data — and are fine to keep in the repo.

If the train set ever changes, ``configs/crop.yaml`` must be regenerated:
``crop_stats.py`` records the split file's sha256 so a mismatch is detectable.

Usage::

    python scripts/make_split.py                       # $HUAWEI_DATA_ROOT, 160/40, seed 42
    python scripts/make_split.py --n-train 160 --seed 42 --out-dir splits
    python scripts/make_split.py --dry-run             # counts only, writes nothing
"""

from __future__ import annotations

import argparse
import datetime as _dt
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # repo root, for `src`

from src.data import DATA_ROOT, list_subjects  # noqa: E402

DEFAULT_N_TRAIN = 160
DEFAULT_N_VAL = 40
DEFAULT_SEED = 42

README_TEMPLATE = """\
# splits/ — subject-level train/val split (PROVISIONAL)

**Status: provisional.** Generated by Role A (`scripts/make_split.py`) using
Role C's documented default: **{n_train} train / {n_val} val, `numpy.random.default_rng({seed})`**.
Role C owns the real split and should either **replace** these files or
**ratify** them as-is.

- `train_ids.txt` — {n_train} subject IDs, one per line, sorted.
- `val_ids.txt` — {n_val} subject IDs, one per line, sorted.

Contents are subject IDs only. No mesh data, no landmarks, no coordinates.

## How it is built

1. `src.data.list_subjects(root)` returns every `mesh/P*.ply` subject ID.
2. The IDs are **sorted** and then shuffled with `default_rng({seed})`, so the
   split depends only on the ID set and the seed, not on filesystem order.
3. The first {n_train} shuffled IDs are train, the next {n_val} are val.

The split is at **subject** level, so a subject's left and right ear always end
up in the same fold by construction: the ear side is never part of the key.

## If the train set changes

`configs/crop.yaml` is derived from `train_ids.txt` **only** and must be
regenerated whenever the train set changes:

    python scripts/crop_stats.py --subject-list splits/train_ids.txt

`crop_stats.py` records the split file's path, sha256 and subject count inside
`crop.yaml`, so a stale config can be detected rather than silently trusted.

Generated {generated} from {n_total} subjects under the dataset root.
"""


def make_split(
    subjects: list[str], n_train: int = DEFAULT_N_TRAIN, seed: int = DEFAULT_SEED
) -> tuple[list[str], list[str]]:
    """Split subject IDs into ``(train, val)``.

    IDs are sorted before shuffling so the result depends only on the *set* of
    IDs and the seed — never on directory listing order.

    Returns two sorted, disjoint lists whose union is all of ``subjects``.
    """
    unique = sorted(set(subjects))
    if len(unique) != len(subjects):
        raise ValueError("duplicate subject IDs in the input list")
    if not 0 < n_train < len(unique):
        raise ValueError(
            f"n_train must be in (0, {len(unique)}), got {n_train}: "
            "cannot split fewer subjects than requested"
        )
    order = np.random.default_rng(seed).permutation(len(unique))
    shuffled = [unique[i] for i in order]
    return sorted(shuffled[:n_train]), sorted(shuffled[n_train:])


def write_ids(path: Path, ids: list[str]) -> None:
    """One ID per line, LF endings, trailing newline."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        for sid in ids:
            fh.write(f"{sid}\n")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--root", type=Path, default=DATA_ROOT,
                    help="dataset root (default: $HUAWEI_DATA_ROOT)")
    ap.add_argument("--out-dir", type=Path, default=Path("splits"),
                    help="directory for train_ids.txt / val_ids.txt / README.md")
    ap.add_argument("--n-train", type=int, default=DEFAULT_N_TRAIN,
                    help=f"training subjects (default {DEFAULT_N_TRAIN}; the rest go to val)")
    ap.add_argument("--seed", type=int, default=DEFAULT_SEED,
                    help=f"numpy default_rng seed (default {DEFAULT_SEED})")
    ap.add_argument("--dry-run", action="store_true", help="print counts but write nothing")
    return ap.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = Path(args.root).expanduser()

    subjects = list_subjects(root)
    print(f"root: {root}\nsubjects found: {len(subjects)}")
    if not subjects:
        print("!! no subjects found")
        return 1

    try:
        train, val = make_split(subjects, n_train=args.n_train, seed=args.seed)
    except ValueError as exc:
        print(f"!! {exc}")
        return 1

    print(f"train: {len(train)}   val: {len(val)}   seed: {args.seed}")
    assert not set(train) & set(val), "train/val overlap"
    assert len(train) + len(val) == len(subjects), "split does not cover every subject"

    if len(train) != DEFAULT_N_TRAIN or len(val) != DEFAULT_N_VAL:
        print(
            f"   note: {len(train)}/{len(val)} is not the documented "
            f"{DEFAULT_N_TRAIN}/{DEFAULT_N_VAL} default - is the subject count right?"
        )

    if args.dry_run:
        print("--dry-run: nothing written")
        return 0

    out = Path(args.out_dir)
    write_ids(out / "train_ids.txt", train)
    write_ids(out / "val_ids.txt", val)
    readme = README_TEMPLATE.format(
        n_train=len(train),
        n_val=len(val),
        seed=args.seed,
        n_total=len(subjects),
        generated=_dt.datetime.now().isoformat(timespec="seconds"),
    )
    with open(out / "README.md", "w", encoding="utf-8", newline="\n") as fh:
        fh.write(readme)

    print(f"wrote {out / 'train_ids.txt'}, {out / 'val_ids.txt'}, {out / 'README.md'}")
    print(
        "\nNEXT: configs/crop.yaml is derived from train_ids.txt only - regenerate it with\n"
        "  python scripts/crop_stats.py --subject-list splits/train_ids.txt"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
